name: Production

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - 'src/**'
      - 'types/**'
      - '*.json'
      - '*.ts'
      - '*.tsx'
      - '*.js'
      - 'serverless.yml'
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'Version (eg. v2.5.0)'
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    name: Deploy to Tencent Cloudbase
    steps:

      - name: Checkout Latest Stable Version
        if: ${{ github.event.inputs.version }} == 'latest'
        uses: actions/checkout@v2

      - name: Checkout ${{ github.event.inputs.version }}
        if: github.event.inputs.version != 'latest'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2.1.6
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - run: yarn build

      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1.1.1
        with:
          secretId: ${{ secrets.TCB_SECRET_ID }}
          secretKey: ${{ secrets.TCB_SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
          staticSrcPath: ./public
          staticIgnore: .git,.github,node_modules,.*,CODEOWNERS,*.md